export const TEXT_BOX_DEFAULT_WIDTH = 300
export const TEXT_BOX_DEFAULT_HEIGHT = 100

export const SHAPE_DEFAULT_WIDTH = 200
export const SHAPE_DEFAULT_HEIGHT = 200

export const WORD_ART_LETTER_WIDTH = 60.02
export const WORD_ART_LETTER_HEIGHT = 132
export const WORD_ART_FONT_SIZE = 100
export const WORD_ART_DEFAULT_WIDTH = WORD_ART_LETTER_WIDTH * 7
export const WORD_ART_DEFAULT_HEIGHT = WORD_ART_FONT_SIZE
